name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish
      continue-on-error: true
      env:
       NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push "**/VxFormGenerator.*.nupkg" -k ${{env.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
      
#    - name: Test
#      run: dotnet test --no-restore --verbosity normal
