version: "3.9"
services:
    webportal:
        build:
          context: .
          dockerfile: ./WebPortal/Presentation/AdsPortal.WebPortal/Dockerfile
        environment:
          - ASPNETCORE_ENVIRONMENT=Production
          - ASPNETCORE_URLS=https://+:443;http://+:80
          - ASPNETCORE_Kestrel__Certificates__Default__Password=secret
          - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
        ports:
            - "5002:80"
            - "5003:443"
        volumes:
            - ~/.aspnet/https:/https:ro
            - adsportal-logs:/app/logs
        depends_on:
            - webapi
    webapi:
        build:
          context: .
          dockerfile: ./WebApi/Presentation/AdsPortal.WebApi/Dockerfile
        environment:
          - ASPNETCORE_ENVIRONMENT=Production
          - ASPNETCORE_URLS=https://+:443;http://+:80
          - ASPNETCORE_Kestrel__Certificates__Default__Password=secret
          - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
        ports:
            - "5000:80"
            - "5001:443"
        depends_on:
          - db
        volumes:
          - ./https:/https:ro
          - filestorage:/app/FileStorage
          - adsportal-logs:/app/logs
    db:
        image: microsoft/mssql-server-linux:latest
        volumes:
          - mssql-server-linux-data:/var/opt/mssql/data
        environment:
            SA_PASSWORD: "Password123@"
            ACCEPT_EULA: "Y"
volumes:
  mssql-server-linux-data:
  filestorage:
  adsportal-logs: